apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.name" . }}
  labels:
    app: {{ .Values.app }}

spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (eq .Values.service.type "NodePort") (.Values.service.nodePort) }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}